In [1]:
#Anmol Gupta
#20BCB0135
#Classification with feature selection

In [14]:
import pandas as pd
import numpy as np
df=pd.read_csv('diabetes.csv')
df.head(5)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [15]:
x=df.drop('Outcome',axis=1)
y=df['Outcome']

In [16]:
# For classificication with feature selection

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [18]:
# Performing feature selection through information gain
from sklearn.feature_selection import mutual_info_classif
mutual_info = mutual_info_classif(x_train, y_train)
mutual_info
mutual_info = pd.Series(mutual_info)
mutual_info.index = x_train.columns
mutual_info.sort_values(ascending=False)

Glucose                     0.120283
BMI                         0.076644
Age                         0.069883
Insulin                     0.068616
SkinThickness               0.046175
Pregnancies                 0.040499
BloodPressure               0.016398
DiabetesPedigreeFunction    0.000000
dtype: float64

In [19]:
#selecting top 5 features
from sklearn.feature_selection import SelectKBest
sel_five_cols = SelectKBest(mutual_info_classif, k=4)
sel_five_cols.fit(x_train, y_train)
x_train.columns[sel_five_cols.get_support()]

Index(['Glucose', 'BloodPressure', 'BMI', 'Age'], dtype='object')

In [20]:
# For back propagation neural network ( multi layer perceptron)

In [21]:
from sklearn.neural_network import MLPClassifier
mlp=MLPClassifier(max_iter=500,activation='relu')
mlp

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_iter=500, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [22]:
mlp.fit(x_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_iter=500, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [23]:
y_pred = mlp.predict(x_test)
y_pred

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:749: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y = np.array(y > threshold, dtype=np.int)


array([0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

In [24]:
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score
print('Confusion Matrix: \n',confusion_matrix(y_test,y_pred),'\n')
print('Classification Report: \n',classification_report(y_test,y_pred),'\n')
print('Accuracy Score:\n',accuracy_score(y_test,y_pred),'\n')

Confusion Matrix: 
 [[120  26]
 [ 32  53]] 

Classification Report: 
               precision    recall  f1-score   support

           0       0.79      0.82      0.81       146
           1       0.67      0.62      0.65        85

    accuracy                           0.75       231
   macro avg       0.73      0.72      0.73       231
weighted avg       0.75      0.75      0.75       231
 

Accuracy Score:
 0.7489177489177489 



In [25]:
print('error rate:{}'.format(accuracy_score(y_test,y_pred)-1))

error rate:-0.25108225108225113


In [26]:
# Support Vector Machine

In [27]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [28]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'poly', random_state = 0)
classifier.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='poly', max_iter=-1, probability=False, random_state=0,
    shrinking=True, tol=0.001, verbose=False)

In [29]:
y_pred = classifier.predict(x_test)

In [30]:
print('Confusion Matrix: \n',confusion_matrix(y_test,y_pred),'\n')
print('Classification Report: \n',classification_report(y_test,y_pred),'\n')
print('Accuracy Score:\n',accuracy_score(y_test,y_pred),'\n')

Confusion Matrix: 
 [[128  18]
 [ 47  38]] 

Classification Report: 
               precision    recall  f1-score   support

           0       0.73      0.88      0.80       146
           1       0.68      0.45      0.54        85

    accuracy                           0.72       231
   macro avg       0.71      0.66      0.67       231
weighted avg       0.71      0.72      0.70       231
 

Accuracy Score:
 0.7186147186147186 



In [31]:
print('error rate:{}'.format(accuracy_score(y_test,y_pred)-1))

error rate:-0.2813852813852814


In [32]:
# K Nearest Neighbours

In [33]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\base.py:908: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  self._y = np.empty(y.shape, dtype=np.int)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [34]:
y_pred=classifier.predict(x_test)

In [35]:
print('Confusion Matrix: \n',confusion_matrix(y_test,y_pred),'\n')
print('Classification Report: \n',classification_report(y_test,y_pred),'\n')
print('Accuracy Score:\n',accuracy_score(y_test,y_pred),'\n')

Confusion Matrix: 
 [[125  21]
 [ 36  49]] 

Classification Report: 
               precision    recall  f1-score   support

           0       0.78      0.86      0.81       146
           1       0.70      0.58      0.63        85

    accuracy                           0.75       231
   macro avg       0.74      0.72      0.72       231
weighted avg       0.75      0.75      0.75       231
 

Accuracy Score:
 0.7532467532467533 



In [36]:
print('error rate:{}'.format(accuracy_score(y_test,y_pred)-1))

error rate:-0.24675324675324672


In [37]:
#Random forest

In [38]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=21,random_state=0)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:32: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:32: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_s

In [39]:
print('Confusion Matrix: \n',confusion_matrix(y_test,y_pred),'\n')
print('Classification Report: \n',classification_report(y_test,y_pred),'\n')
print('Accuracy Score:\n',accuracy_score(y_test,y_pred),'\n')

Confusion Matrix: 
 [[129  17]
 [ 35  50]] 

Classification Report: 
               precision    recall  f1-score   support

           0       0.79      0.88      0.83       146
           1       0.75      0.59      0.66        85

    accuracy                           0.77       231
   macro avg       0.77      0.74      0.75       231
weighted avg       0.77      0.77      0.77       231
 

Accuracy Score:
 0.7748917748917749 



In [40]:
print('error rate:{}'.format(accuracy_score(y_test,y_pred)-1))

error rate:-0.22510822510822515


In [41]:
#Decision Tree

In [42]:
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(x_train, y_train.ravel())

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=42, splitter='best')

In [43]:
y_pred = dt_model.predict(x_test)

In [44]:
print('Confusion Matrix: \n',confusion_matrix(y_test,y_pred),'\n')
print('Classification Report: \n',classification_report(y_test,y_pred),'\n')
print('Accuracy Score:\n',accuracy_score(y_test,y_pred),'\n')

Confusion Matrix: 
 [[105  41]
 [ 30  55]] 

Classification Report: 
               precision    recall  f1-score   support

           0       0.78      0.72      0.75       146
           1       0.57      0.65      0.61        85

    accuracy                           0.69       231
   macro avg       0.68      0.68      0.68       231
weighted avg       0.70      0.69      0.70       231
 

Accuracy Score:
 0.6926406926406926 



In [35]:
print('error rate:{}'.format(accuracy_score(y_test,y_pred)-1))

error rate:-0.2987012987012987


In [36]:
#Naive Bayes

In [37]:
from sklearn.naive_bayes import GaussianNB
nb_model = GaussianNB()
nb_model.fit(x_train, y_train.ravel())

GaussianNB(priors=None, var_smoothing=1e-09)

In [38]:
y_pred= nb_model.predict(x_test)

In [39]:
print('Confusion Matrix: \n',confusion_matrix(y_test,y_pred),'\n')
print('Classification Report: \n',classification_report(y_test,y_pred),'\n')
print('Accuracy Score:\n',accuracy_score(y_test,y_pred),'\n')

Confusion Matrix: 
 [[129  20]
 [ 33  49]] 

Classification Report: 
               precision    recall  f1-score   support

           0       0.80      0.87      0.83       149
           1       0.71      0.60      0.65        82

    accuracy                           0.77       231
   macro avg       0.75      0.73      0.74       231
weighted avg       0.77      0.77      0.77       231
 

Accuracy Score:
 0.7705627705627706 



In [40]:
print('error rate:{}'.format(accuracy_score(y_test,y_pred)-1))

error rate:-0.22943722943722944
