In [1]:
import numpy as np
x=[1,2,3,4]
type(x)

list

In [2]:
nums=np.array(x)
type(nums)

numpy.ndarray

In [4]:
y=[2,3,4,5]
z=[7,3,9,2]
nums_2=np.array([x,y,z])
type(nums_2)

numpy.ndarray

In [5]:
print(nums_2)

[[1 2 3 4]
 [2 3 4 5]
 [7 3 9 2]]


In [6]:
print(nums)

[1 2 3 4]


In [7]:
a=[1,2,3]
nums_3=np.array([x,y,z,a])
print(nums_3)

[list([1, 2, 3, 4]) list([2, 3, 4, 5]) list([7, 3, 9, 2]) list([1, 2, 3])]


<ipython-input-7-6d7651bebb41>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  nums_3=np.array([x,y,z,a])


In [8]:
nums_3=np.array([x,y,z])
print(nums_3)

[[1 2 3 4]
 [2 3 4 5]
 [7 3 9 2]]


In [11]:
a=[1,2,3,4,5]
nums_3=np.array([x,y,z,a])
print(nums_3)

[list([1, 2, 3, 4]) list([2, 3, 4, 5]) list([7, 3, 9, 2])
 list([1, 2, 3, 4, 5])]


<ipython-input-11-da154441f75d>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  nums_3=np.array([x,y,z,a])


In [12]:
type(nums_3)

numpy.ndarray

In [18]:
arr1=np.arange(2,7,2)
print(arr1)

[2 4 6]


In [19]:
zeros=np.zeros(4)

In [20]:
zeros

array([0., 0., 0., 0.])

In [22]:
ones=np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
lin=np.linspace(1,10,73)

In [29]:
lin

array([ 1.   ,  1.125,  1.25 ,  1.375,  1.5  ,  1.625,  1.75 ,  1.875,
        2.   ,  2.125,  2.25 ,  2.375,  2.5  ,  2.625,  2.75 ,  2.875,
        3.   ,  3.125,  3.25 ,  3.375,  3.5  ,  3.625,  3.75 ,  3.875,
        4.   ,  4.125,  4.25 ,  4.375,  4.5  ,  4.625,  4.75 ,  4.875,
        5.   ,  5.125,  5.25 ,  5.375,  5.5  ,  5.625,  5.75 ,  5.875,
        6.   ,  6.125,  6.25 ,  6.375,  6.5  ,  6.625,  6.75 ,  6.875,
        7.   ,  7.125,  7.25 ,  7.375,  7.5  ,  7.625,  7.75 ,  7.875,
        8.   ,  8.125,  8.25 ,  8.375,  8.5  ,  8.625,  8.75 ,  8.875,
        9.   ,  9.125,  9.25 ,  9.375,  9.5  ,  9.625,  9.75 ,  9.875,
       10.   ])

In [30]:
idn=np.eye(3)

In [31]:
idn


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
idn=np.eye(5)
idn

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
ones=np.ones((3,5))
random1=np.random.rand(4,3)
random2=np.random.randint(50,100,10)
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
random1

array([[0.39940923, 0.03460649, 0.08349597],
       [0.60561244, 0.09227924, 0.0471471 ],
       [0.33302854, 0.30734566, 0.47758307],
       [0.86010755, 0.19552061, 0.14089604]])

In [36]:
random2

array([53, 88, 90, 71, 58, 96, 88, 83, 74, 74])

In [39]:
newrandom2=random2.reshape(5,2)

In [40]:
newrandom2


array([[53, 88],
       [90, 71],
       [58, 96],
       [88, 83],
       [74, 74]])

In [41]:
newrandom2.min()

53

In [43]:
newrandom2.argmin()

0

In [44]:
newrandom2.argmax()

5

In [45]:
newrandom1

NameError: name 'newrandom1' is not defined

In [46]:
random2

array([53, 88, 90, 71, 58, 96, 88, 83, 74, 74])

In [47]:
random2[1:5]

array([88, 90, 71, 58])

In [51]:
random2[[0,1]:[3,2]]

TypeError: slice indices must be integers or None or have an __index__ method

In [52]:
newrandom2[0]

array([53, 88])

In [53]:
newrandom2[:,1]

array([88, 71, 96, 83, 74])

In [55]:
newrandom2[0,:]

array([53, 88])

In [57]:
newrandom2[-1,:]

array([74, 74])

In [58]:
random1

array([[0.39940923, 0.03460649, 0.08349597],
       [0.60561244, 0.09227924, 0.0471471 ],
       [0.33302854, 0.30734566, 0.47758307],
       [0.86010755, 0.19552061, 0.14089604]])

In [59]:
random2

array([53, 88, 90, 71, 58, 96, 88, 83, 74, 74])

In [60]:
sum=random1+random2
sum

ValueError: operands could not be broadcast together with shapes (4,3) (10,) 

In [61]:
sum=random1+10
sum

array([[10.39940923, 10.03460649, 10.08349597],
       [10.60561244, 10.09227924, 10.0471471 ],
       [10.33302854, 10.30734566, 10.47758307],
       [10.86010755, 10.19552061, 10.14089604]])

In [62]:
log=np.log(random1)

In [63]:
log

array([[-0.91776874, -3.3637141 , -2.48295687],
       [-0.50151504, -2.38293608, -3.05448279],
       [-1.09952707, -1.17978225, -0.73901716],
       [-0.15069784, -1.6320895 , -1.95973294]])

In [64]:
exp=np.exp(random1)
exp

array([[1.49094364, 1.03521226, 1.08708084],
       [1.83237408, 1.09667101, 1.0482762 ],
       [1.39518712, 1.35981092, 1.61217318],
       [2.36341487, 1.21594385, 1.15130496]])

In [65]:
sqrt=np.sqrt(random1)
sqrt

array([[0.63198832, 0.18602819, 0.2889567 ],
       [0.77821105, 0.30377498, 0.21713383],
       [0.57708625, 0.55438764, 0.69107386],
       [0.92741983, 0.44217712, 0.37536122]])

In [66]:
x=np.array([1,3])
y=np.array([4,5])
zip(x,y)

In [67]:
print(zip(x,y))

In [68]:
dot_product=0
for a,b in zip(x,y):
    dot_product+=a*b
print(dot_product)

19


In [70]:
z=np.array([4,6])
dot_product=0
for a,b,c in zip(x,y,z):
    dot_product+=a*b*c
print(dot_product)

106


In [71]:
list(zip(x,y))

[(1, 4), (3, 5)]

In [72]:
a=x*y
a

array([ 4, 15])

In [73]:
a.sum()

19

In [85]:
x=np.array([[2,3,4],[1,2,3]])

In [79]:
x

array([[2, 3, 4],
       [1, 2, 3],
       [1, 2, 3]])

In [80]:
y=np.array([[2,3],[6,4],[2,7]])
y

array([[2, 3],
       [6, 4],
       [2, 7]])

In [86]:
a=x*y
a.sum()

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [87]:
a=np.dot(x,y)

In [88]:
a

array([[30, 46],
       [20, 32]])

In [89]:
x.shape()

TypeError: 'tuple' object is not callable

In [90]:
x

array([[2, 3, 4],
       [1, 2, 3]])

In [91]:
x.shape()

TypeError: 'tuple' object is not callable

In [92]:
x.shape

(2, 3)

In [93]:
x.reshape(3,2)

array([[2, 3],
       [4, 1],
       [2, 3]])

#Pandas

#pandas

# pandas

In [94]:
import pandas as pd

In [96]:
series1=pd.Series([1,2,3,4])

In [97]:
series1

0    1
1    2
2    3
3    4
dtype: int64

In [98]:
#import sys
#sys._stdout_=sys.stdout
fruits=np.array(['Apple','Mango','Orange','Banana'])
series2=pd.Series(fruits)
series2

0     Apple
1     Mango
2    Orange
3    Banana
dtype: object

In [99]:
series3=pd.Series(['Apple','Mango','Orange','Banana'])
series3

0     Apple
1     Mango
2    Orange
3    Banana
dtype: object

In [100]:
x=['Apple','Mango','Orange','Banana']
series4=pd.Series(x)
series4

0     Apple
1     Mango
2    Orange
3    Banana
dtype: object

In [104]:
df=pd.DataFrame({"Col1":[1,2,3,4],
                 "Col2":['With','Hand','Collumn','Brother'],
                 "Col3":[1.2,4.2,2.4,6.2],
                 "Col4":[True,False,False,True]})
df

Col1     Col2  Col3   Col4
0     1     With   1.2   True
1     2     Hand   4.2  False
2     3  Collumn   2.4  False
3     4  Brother   6.2   True

In [105]:
df.describe

<bound method NDFrame.describe of    Col1     Col2  Col3   Col4
0     1     With   1.2   True
1     2     Hand   4.2  False
2     3  Collumn   2.4  False
3     4  Brother   6.2   True>

In [106]:
df.describe()

Col1      Col3
count  4.000000  4.000000
mean   2.500000  3.500000
std    1.290994  2.181742
min    1.000000  1.200000
25%    1.750000  2.100000
50%    2.500000  3.300000
75%    3.250000  4.700000
max    4.000000  6.200000

In [133]:
data=pd.read_csv('employees.csv')

In [116]:
data.head()

First Name  Gender  Salary Bonus % Senior Management             Team
0    Douglas    Male   97308   6.945              TRUE        Marketing
1     Thomas    Male   61933     NaN              TRUE              NaN
2      Maria  Female  130590  11.858             FALSE          Finance
3      Jerry    Male     NaN    9.34              TRUE          Finance
4      Larry    Male  101004   1.389              TRUE  Client Services

In [111]:
data.describe()

First Name  Gender  Salary Bonus % Senior Management             Team
count         931     852     998     997               932              957
unique        201       3     993     968                 4               13
top       Marilyn  Female  121160  12.182              TRUE  Client Services
freq           11     428       2       3               467              105

In [118]:
missing_values=["n.a","NA","n/a",0," ","n.a."]
data=pd.read_csv('employees.csv',na_values=missing_values)
data.describe()

First Name  Gender  Salary Bonus % Senior Management             Team
count         931     852     998     997               932              957
unique        201       3     993     968                 4               13
top       Marilyn  Female  121160  12.182              TRUE  Client Services
freq           11     428       2       3               467              105

In [114]:
data.head()

First Name  Gender  Salary Bonus % Senior Management             Team
0    Douglas    Male   97308   6.945              TRUE        Marketing
1     Thomas    Male   61933     NaN              TRUE              NaN
2      Maria  Female  130590  11.858             FALSE          Finance
3      Jerry    Male     NaN    9.34              TRUE          Finance
4      Larry    Male  101004   1.389              TRUE  Client Services

In [119]:
data.head(10)

First Name  Gender  Salary Bonus % Senior Management                  Team
0    Douglas    Male   97308   6.945              TRUE             Marketing
1     Thomas    Male   61933     NaN              TRUE                   NaN
2      Maria  Female  130590  11.858             FALSE               Finance
3      Jerry    Male     NaN    9.34              TRUE               Finance
4      Larry    Male  101004   1.389              TRUE       Client Services
5     Dennis    n.a.  115163  10.125             FALSE                 Legal
6       Ruby  Female   65476  10.012              TRUE               Product
7        NaN  Female   45906  11.598               NaN               Finance
8     Angela     NaN     NaN  18.523              TRUE           Engineering
9    Frances  Female  139852   7.524              TRUE  Business Development

In [120]:
print(data.head(10))

  First Name  Gender  Salary Bonus % Senior Management                  Team
0    Douglas    Male   97308   6.945              TRUE             Marketing
1     Thomas    Male   61933     NaN              TRUE                   NaN
2      Maria  Female  130590  11.858             FALSE               Finance
3      Jerry    Male     NaN    9.34              TRUE               Finance
4      Larry    Male  101004   1.389              TRUE       Client Services
5     Dennis    n.a.  115163  10.125             FALSE                 Legal
6       Ruby  Female   65476  10.012              TRUE               Product
7        NaN  Female   45906  11.598               NaN               Finance
8     Angela     NaN     NaN  18.523              TRUE           Engineering
9    Frances  Female  139852   7.524              TRUE  Business Development


In [121]:
missing_values=["n.a","NA","n/a",0," ","n.a."]
data=pd.read_csv('employees.csv',na_values=missing_values)

In [122]:
data.head(10)

First Name  Gender  Salary Bonus % Senior Management                  Team
0    Douglas    Male   97308   6.945              TRUE             Marketing
1     Thomas    Male   61933     NaN              TRUE                   NaN
2      Maria  Female  130590  11.858             FALSE               Finance
3      Jerry    Male     NaN    9.34              TRUE               Finance
4      Larry    Male  101004   1.389              TRUE       Client Services
5     Dennis     NaN  115163  10.125             FALSE                 Legal
6       Ruby  Female   65476  10.012              TRUE               Product
7        NaN  Female   45906  11.598               NaN               Finance
8     Angela     NaN     NaN  18.523              TRUE           Engineering
9    Frances  Female  139852   7.524              TRUE  Business Development

In [123]:
data['First Name'].head()

0    Douglas
1     Thomas
2      Maria
3      Jerry
4      Larry
Name: First Name, dtype: object

In [134]:
#to make the salary column have only integer values
def make_int(i):
    try:
        return int(i)
    except:
        return np.nan
data['Salary']=data['Salary'].map(make_int)    



In [132]:
data['Salary']

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
995   NaN
996   NaN
997   NaN
998   NaN
999   NaN
Name: Salary, Length: 1000, dtype: float64

In [128]:
def make_int(i):
    try:
        return int(i)
    except:
        return np.nan
data['Salary']=map(make_int,data['Salary'])

In [135]:
data['Salary'].head()

0     97308.0
1     61933.0
2    130590.0
3         NaN
4    101004.0
Name: Salary, dtype: float64

In [136]:
data['Salary'].notnull().head(10)

0     True
1     True
2     True
3    False
4     True
5     True
6     True
7     True
8    False
9     True
Name: Salary, dtype: bool

In [139]:
data[data['Salary'].notnull()].head(10)

First Name  Gender    Salary Bonus % Senior Management  \
0     Douglas    Male   97308.0   6.945              TRUE   
1      Thomas    Male   61933.0     NaN              TRUE   
2       Maria  Female  130590.0  11.858             FALSE   
4       Larry    Male  101004.0   1.389              TRUE   
5      Dennis    n.a.  115163.0  10.125             FALSE   
6        Ruby  Female   65476.0  10.012              TRUE   
7         NaN  Female   45906.0  11.598               NaN   
9     Frances  Female  139852.0   7.524              TRUE   
10     Louise  Female   63241.0  15.132              TRUE   
11      Julie  Female  102508.0  12.637              TRUE   

                    Team  
0              Marketing  
1                    NaN  
2                Finance  
4        Client Services  
5                  Legal  
6                Product  
7                Finance  
9   Business Development  
10                   NaN  
11                 Legal

In [138]:
data.shape

(1000, 6)

In [140]:
data['Salary'].head(10)

0     97308.0
1     61933.0
2    130590.0
3         NaN
4    101004.0
5    115163.0
6     65476.0
7     45906.0
8         NaN
9    139852.0
Name: Salary, dtype: float64

In [142]:
data[data['Gender'].notnull()].head(10)

First Name  Gender    Salary Bonus % Senior Management  \
0     Douglas    Male   97308.0   6.945              TRUE   
1      Thomas    Male   61933.0     NaN              TRUE   
2       Maria  Female  130590.0  11.858             FALSE   
3       Jerry    Male       NaN    9.34              TRUE   
4       Larry    Male  101004.0   1.389              TRUE   
5      Dennis    n.a.  115163.0  10.125             FALSE   
6        Ruby  Female   65476.0  10.012              TRUE   
7         NaN  Female   45906.0  11.598               NaN   
9     Frances  Female  139852.0   7.524              TRUE   
10     Louise  Female   63241.0  15.132              TRUE   

                    Team  
0              Marketing  
1                    NaN  
2                Finance  
3                Finance  
4        Client Services  
5                  Legal  
6                Product  
7                Finance  
9   Business Development  
10                   NaN

# Dealing with Missing Values

In [263]:
missing_value_formats=['n.a.',' ','n.a','na','NA','Na',0,'nan']
data=pd.read_csv('employees.csv',na_values=missing_value_formats)

# Dealing with Obscure Values

In [264]:
def make_int(i):
    try:
        return int(i)
    except:
        return np.nan
data['Salary']=data['Salary'].map(make_int)

In [266]:
def make_str(i):
    
        try:
            return str(i)
        except:
            return np.Nan
    
    
data['First Name']=data['First Name'].map(make_str)
data['Gender']=data['Gender'].map(make_str)
data['Team']=data['Team'].map(make_str)

In [150]:
type(data['Senior Management'])

pandas.core.series.Series

In [151]:
x=data['Senior Management'][1]

In [152]:
x

'TRUE'

In [153]:
type(x)

str

In [218]:
data['Senior Management']=data['Senior Management'].map(make_str)

In [163]:
x=data['Bonus %'][0]

In [164]:
x

'6.945'

In [165]:
type(x)

str

In [166]:
x=data['Salary'][0]

In [167]:
x

97308.0

In [168]:
type(x)

numpy.float64

In [190]:
data['Bonus %']=data['Bonus %'].map(make_str)

In [191]:
data.head(10)

First Name  Gender    Salary Bonus % Senior Management                  Team
0    Douglas    Male   97308.0   6.945              TRUE             Marketing
1     Thomas    Male   61933.0     nan              TRUE                   nan
2      Maria  Female  130590.0  11.858             FALSE               Finance
3      Jerry    Male       NaN    9.34              TRUE               Finance
4      Larry    Male  101004.0   1.389              TRUE       Client Services
5     Dennis     nan  115163.0  10.125             FALSE                 Legal
6       Ruby  Female   65476.0  10.012              TRUE               Product
7        nan  Female   45906.0  11.598               nan               Finance
8     Angela     nan       NaN  18.523              TRUE           Engineering
9    Frances  Female  139852.0   7.524              TRUE  Business Development

In [192]:
data.head(10)

First Name  Gender    Salary Bonus % Senior Management                  Team
0    Douglas    Male   97308.0   6.945              TRUE             Marketing
1     Thomas    Male   61933.0     nan              TRUE                   nan
2      Maria  Female  130590.0  11.858             FALSE               Finance
3      Jerry    Male       NaN    9.34              TRUE               Finance
4      Larry    Male  101004.0   1.389              TRUE       Client Services
5     Dennis     nan  115163.0  10.125             FALSE                 Legal
6       Ruby  Female   65476.0  10.012              TRUE               Product
7        nan  Female   45906.0  11.598               nan               Finance
8     Angela     nan       NaN  18.523              TRUE           Engineering
9    Frances  Female  139852.0   7.524              TRUE  Business Development

In [197]:
data[data['Gender'].notnull()]

First Name  Gender    Salary Bonus % Senior Management  \
0      Douglas    Male   97308.0   6.945              TRUE   
1       Thomas    Male   61933.0     nan              TRUE   
2        Maria  Female  130590.0  11.858             FALSE   
3        Jerry    Male       NaN    9.34              TRUE   
4        Larry    Male  101004.0   1.389              TRUE   
..         ...     ...       ...     ...               ...   
995      Henry     nan  132483.0  16.655             FALSE   
996    Phillip    Male   42392.0  19.675             FALSE   
997    Russell    Male   96914.0   1.421             FALSE   
998      Larry    Male   60500.0  11.985             FALSE   
999     Albert    Male  129949.0  10.169              TRUE   

                     Team  
0               Marketing  
1                     nan  
2                 Finance  
3                 Finance  
4         Client Services  
..                    ...  
995          Distribution  
996               Finance  
997               Product  
998  Business Development  
999                 Sales  

[1000 rows x 6 columns]

In [194]:
data

First Name  Gender    Salary Bonus % Senior Management  \
0      Douglas    Male   97308.0   6.945              TRUE   
1       Thomas    Male   61933.0     nan              TRUE   
2        Maria  Female  130590.0  11.858             FALSE   
3        Jerry    Male       NaN    9.34              TRUE   
4        Larry    Male  101004.0   1.389              TRUE   
..         ...     ...       ...     ...               ...   
995      Henry     nan  132483.0  16.655             FALSE   
996    Phillip    Male   42392.0  19.675             FALSE   
997    Russell    Male   96914.0   1.421             FALSE   
998      Larry    Male   60500.0  11.985             FALSE   
999     Albert    Male  129949.0  10.169              TRUE   

                     Team  
0               Marketing  
1                     nan  
2                 Finance  
3                 Finance  
4         Client Services  
..                    ...  
995          Distribution  
996               Finance  
997               Product  
998  Business Development  
999                 Sales  

[1000 rows x 6 columns]

In [196]:
a=np.NaN
a

nan

In [199]:
type(a)

float

In [201]:
a=None
a

In [202]:
type(a)

NoneType

In [203]:
a=NaN
a

NameError: name 'NaN' is not defined

In [205]:
a=np.nan
a.isnull()

AttributeError: 'float' object has no attribute 'isnull'

In [206]:
a=' '
a.notnull()

AttributeError: 'str' object has no attribute 'notnull'

In [210]:
data=pd.DataFrame(data,na_values=missing_value_formats)

TypeError: __init__() got an unexpected keyword argument 'na_values'

In [213]:
x=data['Team'][1]
x

nan

In [214]:
data

First Name  Gender  Salary Bonus % Senior Management                  Team
0      Douglas    Male   97308   6.945              TRUE             Marketing
1       Thomas    Male   61933     NaN              TRUE                   NaN
2        Maria  Female  130590  11.858             FALSE               Finance
3        Jerry    Male     NaN    9.34              TRUE               Finance
4        Larry    Male  101004   1.389              TRUE       Client Services
..         ...     ...     ...     ...               ...                   ...
995      Henry     NaN  132483  16.655             FALSE          Distribution
996    Phillip    Male   42392  19.675             FALSE               Finance
997    Russell    Male   96914   1.421             FALSE               Product
998      Larry    Male   60500  11.985             FALSE  Business Development
999     Albert    Male  129949  10.169              TRUE                 Sales

[1000 rows x 6 columns]

In [215]:
type(x)

float

In [221]:
data=data[data['First Name'] != np.nan]

In [222]:
data

First Name  Gender    Salary Bonus % Senior Management  \
0      Douglas    Male   97308.0   6.945              TRUE   
1       Thomas    Male   61933.0     NaN              TRUE   
2        Maria  Female  130590.0  11.858             FALSE   
3        Jerry    Male       NaN    9.34              TRUE   
4        Larry    Male  101004.0   1.389              TRUE   
..         ...     ...       ...     ...               ...   
995      Henry     nan  132483.0  16.655             FALSE   
996    Phillip    Male   42392.0  19.675             FALSE   
997    Russell    Male   96914.0   1.421             FALSE   
998      Larry    Male   60500.0  11.985             FALSE   
999     Albert    Male  129949.0  10.169              TRUE   

                     Team  
0               Marketing  
1                     nan  
2                 Finance  
3                 Finance  
4         Client Services  
..                    ...  
995          Distribution  
996               Finance  
997               Product  
998  Business Development  
999                 Sales  

[1000 rows x 6 columns]

In [223]:
data=data[data['Gender'] != np.nan]

In [224]:
data

First Name  Gender    Salary Bonus % Senior Management  \
0      Douglas    Male   97308.0   6.945              TRUE   
1       Thomas    Male   61933.0     NaN              TRUE   
2        Maria  Female  130590.0  11.858             FALSE   
3        Jerry    Male       NaN    9.34              TRUE   
4        Larry    Male  101004.0   1.389              TRUE   
..         ...     ...       ...     ...               ...   
995      Henry     nan  132483.0  16.655             FALSE   
996    Phillip    Male   42392.0  19.675             FALSE   
997    Russell    Male   96914.0   1.421             FALSE   
998      Larry    Male   60500.0  11.985             FALSE   
999     Albert    Male  129949.0  10.169              TRUE   

                     Team  
0               Marketing  
1                     nan  
2                 Finance  
3                 Finance  
4         Client Services  
..                    ...  
995          Distribution  
996               Finance  
997               Product  
998  Business Development  
999                 Sales  

[1000 rows x 6 columns]

In [226]:
data

First Name  Gender    Salary Bonus % Senior Management  \
0      Douglas    Male   97308.0   6.945              TRUE   
1       Thomas    Male   61933.0     NaN              TRUE   
2        Maria  Female  130590.0  11.858             FALSE   
3        Jerry    Male       NaN    9.34              TRUE   
4        Larry    Male  101004.0   1.389              TRUE   
..         ...     ...       ...     ...               ...   
995      Henry     nan  132483.0  16.655             FALSE   
996    Phillip    Male   42392.0  19.675             FALSE   
997    Russell    Male   96914.0   1.421             FALSE   
998      Larry    Male   60500.0  11.985             FALSE   
999     Albert    Male  129949.0  10.169              TRUE   

                     Team  
0               Marketing  
1                     nan  
2                 Finance  
3                 Finance  
4         Client Services  
..                    ...  
995          Distribution  
996               Finance  
997               Product  
998  Business Development  
999                 Sales  

[1000 rows x 6 columns]

In [228]:
data.isnull()

First Name  Gender  Salary  Bonus %  Senior Management   Team
0         False   False   False    False              False  False
1         False   False   False     True              False   True
2         False   False   False    False              False  False
3         False   False    True    False              False  False
4         False   False   False    False              False  False
..          ...     ...     ...      ...                ...    ...
995       False    True   False    False              False  False
996       False   False   False    False              False  False
997       False   False   False    False              False  False
998       False   False   False    False              False  False
999       False   False   False    False              False  False

[1000 rows x 6 columns]

In [229]:
data.isnull().values

array([[False, False, False, False, False, False],
       [False, False, False,  True, False,  True],
       [False, False, False, False, False, False],
       ...,
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [231]:
data.isnull().values.any()

True

In [232]:
df.isnull().sum()

Col1    0
Col2    0
Col3    0
Col4    0
dtype: int64

In [233]:
data.isnull().sum()

First Name            69
Gender               149
Salary                 3
Bonus %                3
Senior Management     70
Team                  47
dtype: int64

In [234]:
data


First Name  Gender  Salary Bonus % Senior Management                  Team
0      Douglas    Male   97308   6.945              TRUE             Marketing
1       Thomas    Male   61933     NaN              TRUE                   NaN
2        Maria  Female  130590  11.858             FALSE               Finance
3        Jerry    Male     NaN    9.34              TRUE               Finance
4        Larry    Male  101004   1.389              TRUE       Client Services
..         ...     ...     ...     ...               ...                   ...
995      Henry     NaN  132483  16.655             FALSE          Distribution
996    Phillip    Male   42392  19.675             FALSE               Finance
997    Russell    Male   96914   1.421             FALSE               Product
998      Larry    Male   60500  11.985             FALSE  Business Development
999     Albert    Male  129949  10.169              TRUE                 Sales

[1000 rows x 6 columns]

In [235]:
data.dropna(axis=1,inplace=True)

In [236]:
data

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[1000 rows x 0 columns]

In [238]:
data=pd.read_csv('employees.csv',na_values=missing_value_formats)

In [239]:
data.isnull().values.any()

True

In [240]:
data.dropna(axis=0,inplace=False)

First Name  Gender  Salary Bonus % Senior Management                  Team
0      Douglas    Male   97308   6.945              TRUE             Marketing
2        Maria  Female  130590  11.858             FALSE               Finance
4        Larry    Male  101004   1.389              TRUE       Client Services
6         Ruby  Female   65476  10.012              TRUE               Product
9      Frances  Female  139852   7.524              TRUE  Business Development
..         ...     ...     ...     ...               ...                   ...
994     George    Male   98874   4.479              TRUE             Marketing
996    Phillip    Male   42392  19.675             FALSE               Finance
997    Russell    Male   96914   1.421             FALSE               Product
998      Larry    Male   60500  11.985             FALSE  Business Development
999     Albert    Male  129949  10.169              TRUE                 Sales

[748 rows x 6 columns]

In [241]:
data.dropna(axis=0,how='all',inplace=True)

In [242]:
data


First Name  Gender  Salary Bonus % Senior Management                  Team
0      Douglas    Male   97308   6.945              TRUE             Marketing
1       Thomas    Male   61933     NaN              TRUE                   NaN
2        Maria  Female  130590  11.858             FALSE               Finance
3        Jerry    Male     NaN    9.34              TRUE               Finance
4        Larry    Male  101004   1.389              TRUE       Client Services
..         ...     ...     ...     ...               ...                   ...
995      Henry     NaN  132483  16.655             FALSE          Distribution
996    Phillip    Male   42392  19.675             FALSE               Finance
997    Russell    Male   96914   1.421             FALSE               Product
998      Larry    Male   60500  11.985             FALSE  Business Development
999     Albert    Male  129949  10.169              TRUE                 Sales

[1000 rows x 6 columns]

In [244]:
data.fillna(0,inplace=False)

First Name  Gender  Salary Bonus % Senior Management                  Team
0      Douglas    Male   97308   6.945              TRUE             Marketing
1       Thomas    Male   61933       0              TRUE                     0
2        Maria  Female  130590  11.858             FALSE               Finance
3        Jerry    Male       0    9.34              TRUE               Finance
4        Larry    Male  101004   1.389              TRUE       Client Services
..         ...     ...     ...     ...               ...                   ...
995      Henry       0  132483  16.655             FALSE          Distribution
996    Phillip    Male   42392  19.675             FALSE               Finance
997    Russell    Male   96914   1.421             FALSE               Product
998      Larry    Male   60500  11.985             FALSE  Business Development
999     Albert    Male  129949  10.169              TRUE                 Sales

[1000 rows x 6 columns]

In [245]:
data['Gender'].fillna('No Gender',inplace=False
                     )

0           Male
1           Male
2         Female
3           Male
4           Male
         ...    
995    No Gender
996         Male
997         Male
998         Male
999         Male
Name: Gender, Length: 1000, dtype: object

In [246]:
data.fillna(method='pad',inplace=False)

First Name  Gender  Salary Bonus % Senior Management                  Team
0      Douglas    Male   97308   6.945              TRUE             Marketing
1       Thomas    Male   61933   6.945              TRUE             Marketing
2        Maria  Female  130590  11.858             FALSE               Finance
3        Jerry    Male  130590    9.34              TRUE               Finance
4        Larry    Male  101004   1.389              TRUE       Client Services
..         ...     ...     ...     ...               ...                   ...
995      Henry    Male  132483  16.655             FALSE          Distribution
996    Phillip    Male   42392  19.675             FALSE               Finance
997    Russell    Male   96914   1.421             FALSE               Product
998      Larry    Male   60500  11.985             FALSE  Business Development
999     Albert    Male  129949  10.169              TRUE                 Sales

[1000 rows x 6 columns]

In [247]:
data.fillna(method='bfill',inplace=False)

First Name  Gender  Salary Bonus % Senior Management                  Team
0      Douglas    Male   97308   6.945              TRUE             Marketing
1       Thomas    Male   61933  11.858              TRUE               Finance
2        Maria  Female  130590  11.858             FALSE               Finance
3        Jerry    Male  101004    9.34              TRUE               Finance
4        Larry    Male  101004   1.389              TRUE       Client Services
..         ...     ...     ...     ...               ...                   ...
995      Henry    Male  132483  16.655             FALSE          Distribution
996    Phillip    Male   42392  19.675             FALSE               Finance
997    Russell    Male   96914   1.421             FALSE               Product
998      Larry    Male   60500  11.985             FALSE  Business Development
999     Albert    Male  129949  10.169              TRUE                 Sales

[1000 rows x 6 columns]

In [260]:
data['Team'].fillna(data['Team'].median(),inplace=False)

TypeError: 

In [258]:
data['Salary'].fillna(data['Salary'].mean(),inplace=False)

0       97308.000000
1       61933.000000
2      130590.000000
3       90522.329648
4      101004.000000
           ...      
995    132483.000000
996     42392.000000
997     96914.000000
998     60500.000000
999    129949.000000
Name: Salary, Length: 1000, dtype: float64

In [261]:
data


First Name  Gender    Salary Bonus % Senior Management  \
0      Douglas    Male   97308.0   6.945              TRUE   
1       Thomas    Male   61933.0     NaN              TRUE   
2        Maria  Female  130590.0  11.858             FALSE   
3        Jerry    Male       NaN    9.34              TRUE   
4        Larry    Male  101004.0   1.389              TRUE   
..         ...     ...       ...     ...               ...   
995      Henry     nan  132483.0  16.655             FALSE   
996    Phillip    Male   42392.0  19.675             FALSE   
997    Russell    Male   96914.0   1.421             FALSE   
998      Larry    Male   60500.0  11.985             FALSE   
999     Albert    Male  129949.0  10.169              TRUE   

                     Team  
0               Marketing  
1                     nan  
2                 Finance  
3                 Finance  
4         Client Services  
..                    ...  
995          Distribution  
996               Finance  
997               Product  
998  Business Development  
999                 Sales  

[1000 rows x 6 columns]

In [262]:
data['Team'].fillna(method='bfill',inplace=False)

0                 Marketing
1                       nan
2                   Finance
3                   Finance
4           Client Services
               ...         
995            Distribution
996                 Finance
997                 Product
998    Business Development
999                   Sales
Name: Team, Length: 1000, dtype: object

In [265]:
data.replace(to_replace=np.nan,value=0,inplace=False)

First Name  Gender    Salary Bonus % Senior Management  \
0      Douglas    Male   97308.0   6.945              TRUE   
1       Thomas    Male   61933.0       0              TRUE   
2        Maria  Female  130590.0  11.858             FALSE   
3        Jerry    Male       0.0    9.34              TRUE   
4        Larry    Male  101004.0   1.389              TRUE   
..         ...     ...       ...     ...               ...   
995      Henry       0  132483.0  16.655             FALSE   
996    Phillip    Male   42392.0  19.675             FALSE   
997    Russell    Male   96914.0   1.421             FALSE   
998      Larry    Male   60500.0  11.985             FALSE   
999     Albert    Male  129949.0  10.169              TRUE   

                     Team  
0               Marketing  
1                       0  
2                 Finance  
3                 Finance  
4         Client Services  
..                    ...  
995          Distribution  
996               Finance  
997               Product  
998  Business Development  
999                 Sales  

[1000 rows x 6 columns]

In [269]:
data.replace(to_replace='nan',value=0,inplace=False)

First Name  Gender    Salary Bonus % Senior Management  \
0      Douglas    Male   97308.0   6.945              TRUE   
1       Thomas    Male   61933.0     NaN              TRUE   
2        Maria  Female  130590.0  11.858             FALSE   
3        Jerry    Male       NaN    9.34              TRUE   
4        Larry    Male  101004.0   1.389              TRUE   
..         ...     ...       ...     ...               ...   
995      Henry       0  132483.0  16.655             FALSE   
996    Phillip    Male   42392.0  19.675             FALSE   
997    Russell    Male   96914.0   1.421             FALSE   
998      Larry    Male   60500.0  11.985             FALSE   
999     Albert    Male  129949.0  10.169              TRUE   

                     Team  
0               Marketing  
1                       0  
2                 Finance  
3                 Finance  
4         Client Services  
..                    ...  
995          Distribution  
996               Finance  
997               Product  
998  Business Development  
999                 Sales  

[1000 rows x 6 columns]

In [270]:
a=0
a.notzero()

AttributeError: 'int' object has no attribute 'notzero'

In [271]:
data.replace(to_replace='nan',value=False,inplace=True)

In [272]:
data[data!=False]

First Name  Gender    Salary Bonus % Senior Management  \
0      Douglas    Male   97308.0   6.945              TRUE   
1       Thomas    Male   61933.0     NaN              TRUE   
2        Maria  Female  130590.0  11.858             FALSE   
3        Jerry    Male       NaN    9.34              TRUE   
4        Larry    Male  101004.0   1.389              TRUE   
..         ...     ...       ...     ...               ...   
995      Henry     NaN  132483.0  16.655             FALSE   
996    Phillip    Male   42392.0  19.675             FALSE   
997    Russell    Male   96914.0   1.421             FALSE   
998      Larry    Male   60500.0  11.985             FALSE   
999     Albert    Male  129949.0  10.169              TRUE   

                     Team  
0               Marketing  
1                     NaN  
2                 Finance  
3                 Finance  
4         Client Services  
..                    ...  
995          Distribution  
996               Finance  
997               Product  
998  Business Development  
999                 Sales  

[1000 rows x 6 columns]

In [273]:
data.replace(to_replace=np.nan,value=False,inplace=True)

In [274]:
data

First Name  Gender    Salary Bonus % Senior Management  \
0      Douglas    Male   97308.0   6.945              TRUE   
1       Thomas    Male   61933.0   False              TRUE   
2        Maria  Female  130590.0  11.858             FALSE   
3        Jerry    Male     False    9.34              TRUE   
4        Larry    Male  101004.0   1.389              TRUE   
..         ...     ...       ...     ...               ...   
995      Henry   False  132483.0  16.655             FALSE   
996    Phillip    Male   42392.0  19.675             FALSE   
997    Russell    Male   96914.0   1.421             FALSE   
998      Larry    Male   60500.0  11.985             FALSE   
999     Albert    Male  129949.0  10.169              TRUE   

                     Team  
0               Marketing  
1                   False  
2                 Finance  
3                 Finance  
4         Client Services  
..                    ...  
995          Distribution  
996               Finance  
997               Product  
998  Business Development  
999                 Sales  

[1000 rows x 6 columns]

In [285]:
data=pd.read_csv('employees.csv',na_values=missing_value_formats)

In [276]:
data


First Name  Gender  Salary Bonus % Senior Management                  Team
0      Douglas    Male   97308   6.945              TRUE             Marketing
1       Thomas    Male   61933     NaN              TRUE                   NaN
2        Maria  Female  130590  11.858             FALSE               Finance
3        Jerry    Male     NaN    9.34              TRUE               Finance
4        Larry    Male  101004   1.389              TRUE       Client Services
..         ...     ...     ...     ...               ...                   ...
995      Henry     NaN  132483  16.655             FALSE          Distribution
996    Phillip    Male   42392  19.675             FALSE               Finance
997    Russell    Male   96914   1.421             FALSE               Product
998      Larry    Male   60500  11.985             FALSE  Business Development
999     Albert    Male  129949  10.169              TRUE                 Sales

[1000 rows x 6 columns]

In [288]:
data['Team'].interpolate(method='linear',direction='forward',inplace=True)

In [286]:
data['Team'].isnull().values.sum()

3

In [289]:
data['Team']

0                 Marketing
1                       NaN
2                   Finance
3                   Finance
4           Client Services
               ...         
995            Distribution
996                 Finance
997                 Product
998    Business Development
999                   Sales
Name: Team, Length: 1000, dtype: object

In [291]:
data['Team'].isnull().values.sum()

47

In [293]:
from sklearn import datasets
iris=datasets.load_iris()


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_extraction\image.py:167: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int):
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\datasets\base.py:241: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release no

In [294]:
iris.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

In [295]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [298]:
iris.shape()

AttributeError: shape

In [299]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [300]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [301]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [302]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [303]:
df=pd.DataFrame(iris.data)
df.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2